GET http://localhost:3000/todos/11
###

POST http://localhost:3000/todos
Content-Type: application/json

{
  "id": 12,
  "todo": "Learn GEN AI",
  "priority": "HIGH",
  "status": "IN PROGRESS"
}

###

DELETE http://localhost:3000/todos/10
###


GET http://localhost:3000/todos/?status=TO%20DO
###


GET http://localhost:3000/todos/?priority=LOW
###

GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
###


PUT http://localhost:3000/todos/11
Content-Type: application/json

{ "status": "DONE" }



